export type CategoryId = 'git' | 'http' | 'js-quirks' | 'css' | 'typescript' | 'terminal';

export interface Category {
  id: CategoryId;
  label: string;
  emoji: string;
  description: string;
  color: string;
  iconName: string;
}

export interface Question {
  id: string;
  categoryId: CategoryId;
  prompt: string;
  options: [string, string, string, string];
  correctIndex: 0 | 1 | 2 | 3;
  explanation?: string;
}

export const CATEGORIES: Category[] = [
  {
    id: 'git',
    label: 'Git Commands',
    emoji: '🌿',
    description: 'Test your knowledge of Git commands, flags, and workflows. From basic commits to advanced rebasing — how sharp are your version control skills?',
    color: '#2D6A4F',
    iconName: 'arrow.triangle.branch',
  },
  {
    id: 'http',
    label: 'HTTP Status Codes',
    emoji: '🌐',
    description: 'Do you know your 200s from your 500s? Test whether you can identify what each HTTP status code means — no Googling allowed.',
    color: '#7C3AED',
    iconName: 'globe',
  },
  {
    id: 'js-quirks',
    label: 'JavaScript Quirks',
    emoji: '✨',
    description: 'JavaScript: the language that keeps on giving. Test your knowledge of its most infamous quirks, coercions, and "wat" moments.',
    color: '#D97706',
    iconName: 'curlybraces',
  },
  {
    id: 'css',
    label: 'CSS Tricks',
    emoji: '🎨',
    description: 'Flexbox, specificity, box model madness — CSS looks simple until it isn\'t. Prove you can wrangle styles without crying.',
    color: '#0891B2',
    iconName: 'paintbrush',
  },
  {
    id: 'typescript',
    label: 'TypeScript Types',
    emoji: '🔷',
    description: 'Generics, utility types, and the mysteries of `never`. See if your type-fu is strong enough to survive without `any`.',
    color: '#2563EB',
    iconName: 'function',
  },
  {
    id: 'terminal',
    label: 'Terminal / Shell',
    emoji: '🖥️',
    description: 'Pipes, permissions, signals, and shortcuts. Do you actually know what those commands do, or do you just copy-paste from Stack Overflow?',
    color: '#059669',
    iconName: 'apple.terminal',
  },
];

export const QUESTIONS: Question[] = [
  // Git Commands
  {
    id: 'git-1',
    categoryId: 'git',
    prompt: 'Which command creates a new branch and immediately switches to it?',
    options: [
      'git branch new-branch && git checkout new-branch',
      'git checkout -b new-branch',
      'git switch --create new-branch',
      'Both B and C are correct',
    ],
    correctIndex: 3,
    explanation: 'Both `git checkout -b` and `git switch --create` (or `-c`) create and switch to a new branch.',
  },
  {
    id: 'git-2',
    categoryId: 'git',
    prompt: 'What does `git stash pop` do differently from `git stash apply`?',
    options: [
      'Nothing — they are identical',
      '`pop` applies and removes the stash; `apply` keeps it',
      '`pop` only works on the latest stash',
      '`apply` merges conflicts automatically',
    ],
    correctIndex: 1,
    explanation: '`git stash pop` applies the stash and removes it from the stash list. `git stash apply` applies it but leaves it in the list.',
  },
  {
    id: 'git-3',
    categoryId: 'git',
    prompt: 'What does the `--amend` flag do in `git commit --amend`?',
    options: [
      'Creates a new branch from the last commit',
      'Modifies the most recent commit (message or content)',
      'Reverts the last commit entirely',
      'Stages all modified files',
    ],
    correctIndex: 1,
    explanation: '`--amend` replaces the tip of the current branch with a new commit, letting you fix the message or add forgotten changes.',
  },
  {
    id: 'git-4',
    categoryId: 'git',
    prompt: 'What is a "detached HEAD" state in Git?',
    options: [
      'A corrupted repository',
      'HEAD points directly to a commit, not a branch',
      'A merge conflict that wasn\'t resolved',
      'When a remote branch is deleted',
    ],
    correctIndex: 1,
    explanation: 'Detached HEAD means HEAD points to a specific commit SHA rather than a branch name. Commits made here aren\'t on any branch.',
  },
  {
    id: 'git-5',
    categoryId: 'git',
    prompt: 'What does `git rebase -i HEAD~3` allow you to do?',
    options: [
      'Merge the last 3 branches',
      'Interactively edit the last 3 commits',
      'Revert the last 3 commits',
      'View the diff of the last 3 commits',
    ],
    correctIndex: 1,
    explanation: 'Interactive rebase (`-i`) opens an editor letting you reorder, squash, edit, or drop the specified commits.',
  },
  {
    id: 'git-6',
    categoryId: 'git',
    prompt: 'Which command shows the commit history as a compact one-line-per-commit graph?',
    options: [
      'git log --oneline --graph',
      'git show --compact',
      'git history --tree',
      'git status --verbose',
    ],
    correctIndex: 0,
    explanation: '`git log --oneline --graph` displays an ASCII art graph with short hashes and messages.',
  },
  {
    id: 'git-7',
    categoryId: 'git',
    prompt: 'What does `git cherry-pick <sha>` do?',
    options: [
      'Deletes a commit by its hash',
      'Applies the changes from a specific commit onto the current branch',
      'Creates a tag at the specified commit',
      'Reverts a commit without deleting history',
    ],
    correctIndex: 1,
    explanation: 'Cherry-pick lets you copy a commit from another branch and apply it to your current branch.',
  },
  {
    id: 'git-8',
    categoryId: 'git',
    prompt: 'What is the difference between `git reset --soft` and `git reset --hard`?',
    options: [
      'They are the same; only the message differs',
      '`--soft` keeps staged changes; `--hard` discards everything',
      '`--hard` keeps the working tree; `--soft` clears it',
      '`--soft` resets remote; `--hard` resets local only',
    ],
    correctIndex: 1,
    explanation: '`--soft` moves HEAD but keeps changes staged. `--hard` moves HEAD and discards all changes in working tree and index.',
  },
  {
    id: 'git-9',
    categoryId: 'git',
    prompt: 'What does `.gitignore` do?',
    options: [
      'Removes tracked files from the repository',
      'Prevents specified files/patterns from being tracked by Git',
      'Stores credentials securely',
      'Encrypts files before committing',
    ],
    correctIndex: 1,
    explanation: '`.gitignore` lists patterns of files Git should not track. Already-tracked files are not affected.',
  },
  {
    id: 'git-10',
    categoryId: 'git',
    prompt: 'What command would you use to see which commits introduced a specific string into the codebase?',
    options: [
      'git find -S "string"',
      'git log -S "string"',
      'git search --all "string"',
      'git blame --string "string"',
    ],
    correctIndex: 1,
    explanation: '`git log -S "string"` (the "pickaxe" flag) shows commits that added or removed the given string.',
  },

  // HTTP Status Codes
  {
    id: 'http-1',
    categoryId: 'http',
    prompt: 'What does HTTP status code 418 mean?',
    options: [
      'Payment Required',
      'I\'m a teapot',
      'Service Unavailable',
      'Unprocessable Entity',
    ],
    correctIndex: 1,
    explanation: '418 "I\'m a teapot" is an April Fools\' joke from RFC 2324 (Hyper Text Coffee Pot Control Protocol). Many servers implement it for fun.',
  },
  {
    id: 'http-2',
    categoryId: 'http',
    prompt: 'What is the difference between 401 and 403?',
    options: [
      'They mean the same thing',
      '401 = unauthenticated; 403 = authenticated but unauthorized',
      '401 = server error; 403 = client error',
      '401 = rate limited; 403 = forbidden by firewall',
    ],
    correctIndex: 1,
    explanation: '401 means you aren\'t logged in (or your token is bad). 403 means you\'re authenticated but don\'t have permission.',
  },
  {
    id: 'http-3',
    categoryId: 'http',
    prompt: 'A 301 response means:',
    options: [
      'The resource was found temporarily at a different URL',
      'The resource has moved permanently to a new URL',
      'The request succeeded but has no content',
      'The server is redirecting due to maintenance',
    ],
    correctIndex: 1,
    explanation: '301 is a permanent redirect. Browsers and search engines update their records. 302 is for temporary redirects.',
  },
  {
    id: 'http-4',
    categoryId: 'http',
    prompt: 'What does a 204 status code indicate?',
    options: [
      'The request failed with no error message',
      'The request succeeded but there is no content to return',
      'The content has been partially delivered',
      'The resource was created successfully',
    ],
    correctIndex: 1,
    explanation: '204 No Content is commonly returned by DELETE or PUT endpoints when the operation succeeded but there\'s nothing to send back.',
  },
  {
    id: 'http-5',
    categoryId: 'http',
    prompt: 'What does 429 mean?',
    options: [
      'Too Many Requests (rate limited)',
      'Request Timeout',
      'Payload Too Large',
      'Upgrade Required',
    ],
    correctIndex: 0,
    explanation: '429 Too Many Requests means the client has sent too many requests in a given time. APIs use this for rate limiting.',
  },
  {
    id: 'http-6',
    categoryId: 'http',
    prompt: 'Which status code would a REST API return when a new resource is successfully created?',
    options: [
      '200 OK',
      '204 No Content',
      '201 Created',
      '202 Accepted',
    ],
    correctIndex: 2,
    explanation: '201 Created indicates that the request succeeded and a new resource was created. The response often includes a Location header.',
  },
  {
    id: 'http-7',
    categoryId: 'http',
    prompt: 'What does 503 Service Unavailable typically indicate?',
    options: [
      'The client sent a malformed request',
      'The resource no longer exists',
      'The server is temporarily down or overloaded',
      'Authentication failed',
    ],
    correctIndex: 2,
    explanation: '503 means the server can\'t handle the request right now — usually due to maintenance or being overwhelmed. Retry-After header may be included.',
  },
  {
    id: 'http-8',
    categoryId: 'http',
    prompt: 'What is the 304 Not Modified response used for?',
    options: [
      'Telling the client to use the cached version',
      'Indicating partial content delivery',
      'Redirecting to a new URL',
      'Confirming a file was not changed by the server',
    ],
    correctIndex: 0,
    explanation: '304 is used with conditional requests (If-Modified-Since / ETag). It tells the client the cached version is still valid.',
  },
  {
    id: 'http-9',
    categoryId: 'http',
    prompt: 'What does 422 Unprocessable Entity mean?',
    options: [
      'The request body is too large',
      'The syntax is valid but the semantics are wrong',
      'The endpoint doesn\'t exist',
      'The server can\'t process this file type',
    ],
    correctIndex: 1,
    explanation: '422 means the request was well-formed but contained semantic errors (e.g., validation failures). Common in REST APIs.',
  },
  {
    id: 'http-10',
    categoryId: 'http',
    prompt: 'What\'s the difference between 500 and 502?',
    options: [
      'They\'re identical',
      '500 = internal error on the origin server; 502 = bad response from upstream',
      '500 = client error; 502 = server error',
      '502 only occurs with WebSockets',
    ],
    correctIndex: 1,
    explanation: '500 Internal Server Error is a generic server crash. 502 Bad Gateway means a proxy/load balancer got an invalid response from an upstream server.',
  },

  // JavaScript Quirks
  {
    id: 'js-1',
    categoryId: 'js-quirks',
    prompt: 'What does `typeof null` return in JavaScript?',
    options: [
      '"null"',
      '"undefined"',
      '"object"',
      '"boolean"',
    ],
    correctIndex: 2,
    explanation: 'This is a long-standing bug in JavaScript. `typeof null === "object"` — it\'s never been fixed to avoid breaking existing code.',
  },
  {
    id: 'js-2',
    categoryId: 'js-quirks',
    prompt: 'What is the result of `0.1 + 0.2 === 0.3` in JavaScript?',
    options: [
      'true',
      'false',
      'It throws an error',
      'undefined',
    ],
    correctIndex: 1,
    explanation: 'Due to IEEE 754 floating-point arithmetic, `0.1 + 0.2` equals `0.30000000000000004`. Use `Number.EPSILON` for comparisons.',
  },
  {
    id: 'js-3',
    categoryId: 'js-quirks',
    prompt: 'What does `[] + []` evaluate to?',
    options: [
      '[]',
      '0',
      '"" (empty string)',
      'undefined',
    ],
    correctIndex: 2,
    explanation: 'Both arrays are coerced to empty strings, then concatenated: `"" + "" = ""`.',
  },
  {
    id: 'js-4',
    categoryId: 'js-quirks',
    prompt: 'What does `[] + {}` evaluate to?',
    options: [
      '{}',
      '"[object Object]"',
      'undefined',
      '0',
    ],
    correctIndex: 1,
    explanation: '`[]` becomes `""`, `{}` becomes `"[object Object]"`, so `"" + "[object Object]" = "[object Object]"`.',
  },
  {
    id: 'js-5',
    categoryId: 'js-quirks',
    prompt: 'What is the result of `typeof NaN`?',
    options: [
      '"NaN"',
      '"undefined"',
      '"number"',
      '"error"',
    ],
    correctIndex: 2,
    explanation: 'Despite standing for "Not a Number", `NaN` has type `"number"`. Also, `NaN !== NaN` — use `Number.isNaN()` to check for it.',
  },
  {
    id: 'js-6',
    categoryId: 'js-quirks',
    prompt: 'What does `"5" - 3` evaluate to in JavaScript?',
    options: [
      '"53" (string)',
      'NaN',
      '2 (number)',
      '53 (number)',
    ],
    correctIndex: 2,
    explanation: 'The `-` operator always coerces to numbers, so `"5"` becomes `5` and the result is `2`. The `+` operator would concatenate instead.',
  },
  {
    id: 'js-7',
    categoryId: 'js-quirks',
    prompt: 'What is the value of `!!""` in JavaScript?',
    options: [
      'true',
      'false',
      '"" (empty string)',
      'undefined',
    ],
    correctIndex: 1,
    explanation: '`""` is falsy. `!""` is `true`. `!!""` is `false`. Double negation converts any value to its boolean equivalent.',
  },
  {
    id: 'js-8',
    categoryId: 'js-quirks',
    prompt: 'What does `console.log(1 < 2 < 3)` print?',
    options: [
      'false',
      'true',
      'It throws a TypeError',
      'NaN',
    ],
    correctIndex: 1,
    explanation: '`1 < 2` is `true`, then `true < 3` coerces `true` to `1`, so `1 < 3` is `true`. Chained comparisons don\'t work mathematically in JS.',
  },
  {
    id: 'js-9',
    categoryId: 'js-quirks',
    prompt: 'What does `console.log(3 > 2 > 1)` print?',
    options: [
      'true',
      'false',
      'It throws a TypeError',
      'undefined',
    ],
    correctIndex: 1,
    explanation: '`3 > 2` is `true`, then `true > 1` coerces `true` to `1`, so `1 > 1` is `false`. Gotcha!',
  },
  {
    id: 'js-10',
    categoryId: 'js-quirks',
    prompt: 'What is the result of `+[]` in JavaScript?',
    options: [
      'undefined',
      'NaN',
      '0',
      '""',
    ],
    correctIndex: 2,
    explanation: 'The unary `+` coerces `[]` to a number: `[]` → `""` → `0`. So `+[] === 0`.',
  },

  // CSS Tricks
  {
    id: 'css-1',
    categoryId: 'css',
    prompt: 'What is the default value of the `position` property?',
    options: [
      'relative',
      'absolute',
      'static',
      'inherit',
    ],
    correctIndex: 2,
    explanation: 'Every element starts with `position: static`. Positioned elements (relative, absolute, fixed, sticky) opt in to the positioned layout.',
  },
  {
    id: 'css-2',
    categoryId: 'css',
    prompt: '`z-index` only works on elements that are:',
    options: [
      'Block-level',
      'Positioned (not static) or flex/grid children',
      'Inside a float',
      'Display inline-block',
    ],
    correctIndex: 1,
    explanation: '`z-index` has no effect on `position: static` elements. It works on positioned elements and flex/grid items.',
  },
  {
    id: 'css-3',
    categoryId: 'css',
    prompt: 'What does `box-sizing: border-box` change?',
    options: [
      'Width and height include padding and border',
      'Margins are included in the element size',
      'It disables the box model',
      'It only affects inline elements',
    ],
    correctIndex: 0,
    explanation: 'With `border-box`, the declared width/height includes padding and border. The default `content-box` adds them on top.',
  },
  {
    id: 'css-4',
    categoryId: 'css',
    prompt: 'Which has the highest specificity?',
    options: [
      'A class selector `.btn`',
      'An element selector `div`',
      'An ID selector `#main`',
      'A pseudo-class `:hover`',
    ],
    correctIndex: 2,
    explanation: 'Specificity order: inline styles > ID > class/pseudo-class/attribute > element/pseudo-element. `#main` beats `.btn`.',
  },
  {
    id: 'css-5',
    categoryId: 'css',
    prompt: 'What is the default `flex-direction` value?',
    options: [
      'column',
      'row',
      'row-reverse',
      'inherit',
    ],
    correctIndex: 1,
    explanation: 'Flexbox lays items out in a `row` by default (left-to-right in LTR languages).',
  },
  {
    id: 'css-6',
    categoryId: 'css',
    prompt: 'What is the difference between `display: none` and `visibility: hidden`?',
    options: [
      'They behave identically',
      '`none` removes from flow; `hidden` keeps the space',
      '`hidden` removes from flow; `none` keeps the space',
      '`visibility: hidden` also hides child elements permanently',
    ],
    correctIndex: 1,
    explanation: '`display: none` removes the element from the layout entirely. `visibility: hidden` hides it but still reserves its space.',
  },
  {
    id: 'css-7',
    categoryId: 'css',
    prompt: 'What value does `flex-shrink` default to?',
    options: [
      '0',
      '1',
      'auto',
      'none',
    ],
    correctIndex: 1,
    explanation: '`flex-shrink` defaults to `1`, meaning items will shrink to prevent overflow. Set it to `0` to prevent shrinking.',
  },
  {
    id: 'css-8',
    categoryId: 'css',
    prompt: 'Which property creates a new stacking context?',
    options: [
      '`margin: auto`',
      '`opacity` less than 1',
      '`display: block`',
      '`padding: 0`',
    ],
    correctIndex: 1,
    explanation: 'Setting `opacity` to anything less than 1 creates a new stacking context. So do `transform`, `filter`, `will-change`, and others.',
  },
  {
    id: 'css-9',
    categoryId: 'css',
    prompt: 'What does `margin: 0 auto` do on a block element with a set width?',
    options: [
      'Removes all margins',
      'Centers the element horizontally',
      'Centers the element vertically',
      'Sets margin to the browser default',
    ],
    correctIndex: 1,
    explanation: '`auto` left/right margins distribute remaining space equally, centering the block element horizontally.',
  },
  {
    id: 'css-10',
    categoryId: 'css',
    prompt: 'What happens when two adjacent vertical margins meet?',
    options: [
      'They add together',
      'The larger margin wins (margin collapse)',
      'The element breaks out of flow',
      'Both margins are set to zero',
    ],
    correctIndex: 1,
    explanation: 'Vertical margins collapse: the bigger one wins instead of both being applied. This doesn\'t happen with horizontal margins or in flex/grid.',
  },

  // TypeScript Types
  {
    id: 'ts-1',
    categoryId: 'typescript',
    prompt: 'What is the key difference between `unknown` and `any`?',
    options: [
      'There is no difference',
      '`unknown` requires type narrowing before use; `any` skips all checks',
      '`any` is stricter than `unknown`',
      '`unknown` is only for function return types',
    ],
    correctIndex: 1,
    explanation: '`unknown` is the type-safe counterpart to `any`. You must narrow it (type guard, assertion) before using it.',
  },
  {
    id: 'ts-2',
    categoryId: 'typescript',
    prompt: 'What does `keyof T` produce?',
    options: [
      'An array of property names',
      'A union of the property name literal types',
      'The values of T',
      'A mapped type',
    ],
    correctIndex: 1,
    explanation: '`keyof T` yields a union of string (or number/symbol) literal types representing the property names of `T`.',
  },
  {
    id: 'ts-3',
    categoryId: 'typescript',
    prompt: 'When does the `never` type appear?',
    options: [
      'When a function returns undefined',
      'When a value can\'t logically exist (e.g., exhaustive checks, functions that always throw)',
      'Only in generic constraints',
      'When a variable is uninitialized',
    ],
    correctIndex: 1,
    explanation: '`never` represents impossible values — functions that never return, or type branches that can\'t happen after exhaustive narrowing.',
  },
  {
    id: 'ts-4',
    categoryId: 'typescript',
    prompt: 'What does `Partial<T>` do?',
    options: [
      'Makes all properties required',
      'Makes all properties optional',
      'Removes all methods',
      'Picks only string properties',
    ],
    correctIndex: 1,
    explanation: '`Partial<T>` makes every property of `T` optional (`?`). Its opposite is `Required<T>`.',
  },
  {
    id: 'ts-5',
    categoryId: 'typescript',
    prompt: 'What does `as const` do to an object literal?',
    options: [
      'Makes it mutable',
      'Converts it to a class',
      'Makes all properties `readonly` with literal types',
      'Freezes it at runtime',
    ],
    correctIndex: 2,
    explanation: '`as const` makes TypeScript infer the narrowest literal types and marks everything `readonly`. It\'s a compile-time assertion only.',
  },
  {
    id: 'ts-6',
    categoryId: 'typescript',
    prompt: 'What does `Omit<T, K>` produce?',
    options: [
      'A type with only the properties in K',
      'A type with all properties of T except those in K',
      'A union of T and K',
      'An intersection of T and K',
    ],
    correctIndex: 1,
    explanation: '`Omit<T, K>` creates a new type by removing the keys `K` from `T`. The inverse is `Pick<T, K>`.',
  },
  {
    id: 'ts-7',
    categoryId: 'typescript',
    prompt: 'What is a discriminated union in TypeScript?',
    options: [
      'A union of primitive types',
      'A union where each member has a common literal property used for narrowing',
      'Two interfaces merged together',
      'A generic with constraints',
    ],
    correctIndex: 1,
    explanation: 'A discriminated union uses a shared literal field (like `type: "circle" | "square"`) so TypeScript can narrow each branch in a switch.',
  },
  {
    id: 'ts-8',
    categoryId: 'typescript',
    prompt: 'What does the `infer` keyword do?',
    options: [
      'Infers a type variable within a conditional type',
      'Automatically infers function parameter types',
      'Creates a new generic constraint',
      'Converts `any` to `unknown`',
    ],
    correctIndex: 0,
    explanation: '`infer` lets you extract a type inside a conditional type, e.g., `T extends Promise<infer U> ? U : T` unwraps a Promise.',
  },
  {
    id: 'ts-9',
    categoryId: 'typescript',
    prompt: 'Which statement about `interface` vs `type` is correct?',
    options: [
      'They are 100% identical',
      '`interface` supports declaration merging; `type` does not',
      '`type` can extend other types; `interface` cannot',
      '`interface` is deprecated in favor of `type`',
    ],
    correctIndex: 1,
    explanation: 'Interfaces can be re-declared and merged. Type aliases are closed after creation. Both support extension, just differently.',
  },
  {
    id: 'ts-10',
    categoryId: 'typescript',
    prompt: 'What does `satisfies` do in TypeScript?',
    options: [
      'Casts a value to a wider type',
      'Validates a value matches a type without widening the inferred type',
      'Throws a runtime error if types don\'t match',
      'It is not a valid TypeScript keyword',
    ],
    correctIndex: 1,
    explanation: '`satisfies` checks that a value conforms to a type while keeping the narrower inferred type, unlike `as` which widens it.',
  },

  // Terminal / Shell
  {
    id: 'term-1',
    categoryId: 'terminal',
    prompt: 'What does the `|` (pipe) operator do?',
    options: [
      'Runs two commands in parallel',
      'Passes stdout of the left command to stdin of the right',
      'Redirects stderr to a file',
      'Appends output to a file',
    ],
    correctIndex: 1,
    explanation: 'The pipe connects the standard output of one command to the standard input of the next, enabling powerful command chaining.',
  },
  {
    id: 'term-2',
    categoryId: 'terminal',
    prompt: 'What does `chmod 755 file.sh` set?',
    options: [
      'Owner: rwx, Group: rwx, Others: rwx',
      'Owner: rwx, Group: r-x, Others: r-x',
      'Owner: rw-, Group: r--, Others: r--',
      'Owner: rwx, Group: rw-, Others: ---',
    ],
    correctIndex: 1,
    explanation: '7 = rwx (4+2+1), 5 = r-x (4+0+1). So 755 gives the owner full access and everyone else read + execute.',
  },
  {
    id: 'term-3',
    categoryId: 'terminal',
    prompt: 'What does `$?` contain in bash?',
    options: [
      'The current process ID',
      'The exit code of the last command',
      'The number of arguments passed',
      'The name of the current script',
    ],
    correctIndex: 1,
    explanation: '`$?` holds the exit status of the most recently executed command. `0` means success, anything else is an error.',
  },
  {
    id: 'term-4',
    categoryId: 'terminal',
    prompt: 'What is the difference between `>` and `>>`?',
    options: [
      '`>` appends; `>>` overwrites',
      '`>` overwrites the file; `>>` appends to it',
      'They are identical',
      '`>>` writes to stderr instead',
    ],
    correctIndex: 1,
    explanation: '`>` truncates the file and writes. `>>` appends to the existing content. Both create the file if it doesn\'t exist.',
  },
  {
    id: 'term-5',
    categoryId: 'terminal',
    prompt: 'What signal does `kill -9` send?',
    options: [
      'SIGTERM',
      'SIGINT',
      'SIGKILL',
      'SIGHUP',
    ],
    correctIndex: 2,
    explanation: '`kill -9` sends SIGKILL, which cannot be caught or ignored — the process is forcefully terminated by the kernel.',
  },
  {
    id: 'term-6',
    categoryId: 'terminal',
    prompt: 'What does `&&` between two commands do?',
    options: [
      'Runs both commands regardless of success',
      'Runs the second command only if the first succeeds',
      'Runs both commands in the background',
      'Pipes output between commands',
    ],
    correctIndex: 1,
    explanation: '`&&` is a logical AND — the right side only executes if the left side exits with code 0 (success). Use `||` for "or".',
  },
  {
    id: 'term-7',
    categoryId: 'terminal',
    prompt: 'What does `~` represent in a shell path?',
    options: [
      'The root directory `/`',
      'The current directory',
      'The current user\'s home directory',
      'The previous directory',
    ],
    correctIndex: 2,
    explanation: '`~` expands to `$HOME`, the current user\'s home directory. `~user` expands to that user\'s home directory.',
  },
  {
    id: 'term-8',
    categoryId: 'terminal',
    prompt: 'What signal does Ctrl+C send to a running process?',
    options: [
      'SIGKILL',
      'SIGTERM',
      'SIGINT',
      'SIGSTOP',
    ],
    correctIndex: 2,
    explanation: 'Ctrl+C sends SIGINT (interrupt). Unlike SIGKILL, the process can catch it and clean up gracefully.',
  },
  {
    id: 'term-9',
    categoryId: 'terminal',
    prompt: 'What does `2>&1` do in a shell command?',
    options: [
      'Redirects stdin to stdout',
      'Redirects stderr to stdout',
      'Duplicates file descriptor 1 to 2',
      'Silences all output',
    ],
    correctIndex: 1,
    explanation: '`2>&1` redirects file descriptor 2 (stderr) to wherever file descriptor 1 (stdout) is currently going.',
  },
  {
    id: 'term-10',
    categoryId: 'terminal',
    prompt: 'What does `xargs` do?',
    options: [
      'Extracts command-line arguments from a binary',
      'Builds and executes commands from standard input',
      'Parses XML arguments',
      'Lists all environment variables',
    ],
    correctIndex: 1,
    explanation: '`xargs` reads items from stdin and executes a command with those items as arguments. Often paired with `find` or `grep`.',
  },
];

export const FEEDBACK = {
  correct: [
    "Correct! There's hope for you yet.",
    'Look at you, remembering things!',
    'Right! The neurons still fire.',
    "Correct! Who needs AI anyway?",
    'Nailed it. Your rubber duck would be proud.',
    'You still got it. Barely.',
  ],
  incorrect: [
    'Nope. Maybe ask ChatGPT?',
    'Wrong. The AI has taken this one from you.',
    'Incorrect. This is why we built autocomplete.',
    "Not quite. Stack Overflow is judging you.",
    'Wrong! Your senior dev is sighing somewhere.',
    'Nah. Back to the docs with you.',
  ],
};

export function getQuestionsForCategory(id: CategoryId): Question[] {
  return QUESTIONS.filter((q) => q.categoryId === id);
}

export function getCategoryById(id: CategoryId): Category | undefined {
  return CATEGORIES.find((c) => c.id === id);
}
